---
abstract: "Adds a Coderwall 'endorse' button to README Markdown file (DEPRECATED)"
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  JSON::Any: '0'
  Test::DZil: '0'
  Test::More: '0.96'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.033, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-CoderwallEndorse
provides:
  Dist::Zilla::Plugin::CoderwallEndorse:
    file: lib/Dist/Zilla/Plugin/CoderwallEndorse.pm
    version: v0.2.1
requires:
  Dist::Zilla::Role::File::ChangeNotification: '0'
  Dist::Zilla::Role::FileMunger: '0'
  Dist::Zilla::Role::Plugin: '0'
  List::Util: '0'
  Moose: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dist-Zilla-Plugin-CoderwallEndorse/issues
  homepage: https://github.com/yanick/Dist-Zilla-Plugin-CoderwallEndorse
  repository: https://github.com/yanick/Dist-Zilla-Plugin-CoderwallEndorse.git
version: 0.2.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_deprecated: 1
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
